name: CodeClimate Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: CodeClimate Coverage
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g jest
    - run: npm install
    - uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 78d0c5eab6f8f0192f830de7204d3d15cea41a8b485d839f86de4b249d84979b
      with:
        coverageCommand: npm run coverage
